#services:
#  library-backend:
#    build:
#      context: ./laba
#      dockerfile: ./Dockerfile
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    volumes:
#      - ./laba:/app
#    restart: unless-stopped
#    depends_on:
#      - database
#
#  database:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_DB=java
#      - POSTGRES_USER=cats
#      - POSTGRES_PASSWORD=egerin
#
##  library-frontend:
##    build:
##      context: ./frontend
##      dockerfile: ./Dockerfile
##    expose:
##      - 8080
##    ports:
##      - "8080:8080"
##    volumes:
##      - ./frontend:/frontend
##    restart: unless-stopped

volumes:
  pg_cats:

services:
  backend:
    restart: always
    build:
      context: ./laba
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cats_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://cats_db:5432/java'


  cats_db:
    image: postgres
    container_name: cats_db_java
    restart: always
    environment:
      - POSTGRES_DB=java
      - POSTGRES_USER=cats
      - POSTGRES_PASSWORD=egerin
    ports:
      - "5432:5432"
